### ISSUE TITLE
[Bug]: GHA checkout problem in PRs

### ISSUE THREAD

**Issue by szepeviktor** [luminarix/enum-concern#8]
### What happened?

`ref: sa`

### How to reproduce the bug

https://github.com/luminarix/enum-concern/blob/b0628939d0a3f96e4640ad72cf16394ee830fa41/.github/workflows/fix-php-code-style-issues.yml#L23

**Comment by xHeaven** [comment]
Should be fixed in https://github.com/luminarix/enum-concern/pull/9
